### ISSUE TITLE
TCP Modbus Client

### ISSUE THREAD

**Issue by Yusuftunch** [epsilonrt/modbus-ethercard#1]
Thank you for your library but I couldn't see Client in the linrary, I wish it has client

**Comment by epsilonrt** [comment]
As it is written in the [README](https://github.com/epsilonrt/modbus-ethercard):
"In the current version the library allows the **Arduino operate as a slave**, supporting Modbus over TCP."
Slave = Server !

**Comment by Yusuftunch** [comment]
I read your notes carefully and realized that there is no client in TCP modbus in this version. That's why I wish there was.:-)

**Comment by Yusuftunch** [comment]
I tried with many library I think yours are free for error only:-) The others have more problems.
